Data frames - creating

In [7]:
import numpy as np
import pandas as pd

In [9]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
#using list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns =["name","age", "city","salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
#Create a DataFrame from a List of Dictionaries
import pandas as pd

data = [
    {"Name": "Alice", "Age": 20},
    {"Name": "Bob", "Age": 22},
    {"Name": "Charlie", "Age": 21}
]

df = pd.DataFrame(data)

print(df)

      Name  Age
0    Alice   20
1      Bob   22
2  Charlie   21

In [31]:
#selection and indxing of column
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2["name"]  #single column access

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: object

In [ ]:
df2[["name", "city"]]    #multi column access

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [15]:
#new column
df2["Designation"]= ["doctor","eng","doc","eng"]

In [16]:
df2

    name  age      city  salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000         doc
3  Linda   42    London   85000         eng

In [ ]:
#remove columns temporary
df2.drop("Designation",axis=1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [20]:
#remove column permanent
df2.drop("Designation",axis=1, inplace=True)

In [21]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [32]:
#remove multiple columns
df2.drop(["city","salary"],axis=1)

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [11]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
#remove row
df2.drop(0,axis=0)

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

selecting rows

In [ ]:
df2.loc[1]

name       Anna
age          34
city      Paris
salary    70000
Name: 1, dtype: object

In [37]:
df2.loc[[1,2]]

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [39]:
df2.iloc[3]

name       Linda
age           42
city      London
salary     85000
Name: 3, dtype: object

Selecting subsets of rows and columns

In [12]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2.loc[[0,1]][["city","salary"]]

       city  salary
0  New York   65000
1     Paris   70000

In [15]:
df2.loc[[2,3]][["name","age"]]

    name  age
2  Peter   29
3  Linda   42

Conditional selection

In [16]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
#i want people whose age is above the 30
df2[df2["age"]>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [24]:
#i want people whose age is above 30 and live in paris
df2[(df2["age"]>30) & (df2["city"] == 'Paris')]

   name  age   city  salary
1  Anna   34  Paris   70000

In [ ]:
df2[(df2["age"]>30) | (df2["salary"]>60000)]  #or

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2[~(df2["age"]>30)]   #not

    name  age      city  salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000