Missing Data

Finding missing Number

In [2]:
import numpy as np
import pandas as pd

In [16]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.isnull()   #find is any nan value

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [19]:
df.isnull().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [20]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [21]:
df[df.isnull().any(axis=1)]

     A  B    C    D
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Removing missing number

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.dropna(
)

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) #Keep rows with at least 3 non-missing values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [25]:
df.dropna(axis=1)

   B
0  1
1  2
2  3
3  4
4  5

FIlling missing number

In [26]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [29]:
df.fillna(5)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  5.0  3  3.0  5.0
3  4.0  4  5.0  5.0
4  5.0  5  5.0  5.0

In [30]:
#filling woth different values
values= {'A':0,'B':100, 'C':900,'D':300}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  900.0  300.0
4  5.0  5  900.0    5.0

In [31]:
#filling with means
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0